[project]
name = "endjin-local-spark"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.1",
    "pyarrow>=21.0.0",
    "pyspark==3.5.0",
    "numpy<2.0", # fix np.nan problem
    "ipykernel>=6.30.1",
]
